// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ConnectedGridAccelerator.ManagementApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExtendedPropertyRetrieve
    {
        /// <summary>
        /// Initializes a new instance of the ExtendedPropertyRetrieve class.
        /// </summary>
        public ExtendedPropertyRetrieve()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExtendedPropertyRetrieve class.
        /// </summary>
        /// <param name="name">Property key name</param>
        /// <param name="value">The property's value</param>
        /// <param name="dataType">The declared datatype of the property
        /// key</param>
        public ExtendedPropertyRetrieve(string name = default(string), string value = default(string), string dataType = default(string))
        {
            Name = name;
            Value = value;
            DataType = dataType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets property key name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the property's value
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Gets or sets the declared datatype of the property key
        /// </summary>
        [JsonProperty(PropertyName = "dataType")]
        public string DataType { get; set; }

    }
}
