// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ConnectedGridAccelerator.ManagementApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FilterQueryOption
    {
        /// <summary>
        /// Initializes a new instance of the FilterQueryOption class.
        /// </summary>
        public FilterQueryOption()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FilterQueryOption class.
        /// </summary>
        public FilterQueryOption(ODataQueryContext context = default(ODataQueryContext), object validator = default(object), FilterClause filterClause = default(FilterClause), string rawValue = default(string))
        {
            Context = context;
            Validator = validator;
            FilterClause = filterClause;
            RawValue = rawValue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "context")]
        public ODataQueryContext Context { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "validator")]
        public object Validator { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "filterClause")]
        public FilterClause FilterClause { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rawValue")]
        public string RawValue { get; private set; }

    }
}
