// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ConnectedGridAccelerator.ManagementApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class IEdmModel
    {
        /// <summary>
        /// Initializes a new instance of the IEdmModel class.
        /// </summary>
        public IEdmModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IEdmModel class.
        /// </summary>
        public IEdmModel(System.Collections.Generic.IList<IEdmSchemaElement> schemaElements = default(System.Collections.Generic.IList<IEdmSchemaElement>), System.Collections.Generic.IList<IEdmVocabularyAnnotation> vocabularyAnnotations = default(System.Collections.Generic.IList<IEdmVocabularyAnnotation>), System.Collections.Generic.IList<IEdmModel> referencedModels = default(System.Collections.Generic.IList<IEdmModel>), object directValueAnnotationsManager = default(object))
        {
            SchemaElements = schemaElements;
            VocabularyAnnotations = vocabularyAnnotations;
            ReferencedModels = referencedModels;
            DirectValueAnnotationsManager = directValueAnnotationsManager;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schemaElements")]
        public System.Collections.Generic.IList<IEdmSchemaElement> SchemaElements { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "vocabularyAnnotations")]
        public System.Collections.Generic.IList<IEdmVocabularyAnnotation> VocabularyAnnotations { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referencedModels")]
        public System.Collections.Generic.IList<IEdmModel> ReferencedModels { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "directValueAnnotationsManager")]
        public object DirectValueAnnotationsManager { get; private set; }

    }
}
