// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ConnectedGridAccelerator.ManagementApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Payload when retrieving a key store
    /// </summary>
    public partial class KeyStoreRetrieve
    {
        /// <summary>
        /// Initializes a new instance of the KeyStoreRetrieve class.
        /// </summary>
        public KeyStoreRetrieve()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KeyStoreRetrieve class.
        /// </summary>
        /// <param name="id">Unique identifier</param>
        /// <param name="spaceId">Id of the parent space container</param>
        /// <param name="keys">Security keys</param>
        /// <param name="space">Parent space</param>
        public KeyStoreRetrieve(System.Guid id, string name, System.Guid spaceId, string description = default(string), string fullName = default(string), System.Collections.Generic.IList<string> spacePaths = default(System.Collections.Generic.IList<string>), System.Collections.Generic.IList<SecurityKeyRetrieve> keys = default(System.Collections.Generic.IList<SecurityKeyRetrieve>), SpaceRetrieve space = default(SpaceRetrieve))
        {
            Id = id;
            Name = name;
            Description = description;
            SpaceId = spaceId;
            FullName = fullName;
            SpacePaths = spacePaths;
            Keys = keys;
            Space = space;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets unique identifier
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets id of the parent space container
        /// </summary>
        [JsonProperty(PropertyName = "spaceId")]
        public System.Guid SpaceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fullName")]
        public string FullName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "spacePaths")]
        public System.Collections.Generic.IList<string> SpacePaths { get; set; }

        /// <summary>
        /// Gets or sets security keys
        /// </summary>
        [JsonProperty(PropertyName = "keys")]
        public System.Collections.Generic.IList<SecurityKeyRetrieve> Keys { get; set; }

        /// <summary>
        /// Gets or sets parent space
        /// </summary>
        [JsonProperty(PropertyName = "space")]
        public SpaceRetrieve Space { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Space != null)
            {
                Space.Validate();
            }
        }
    }
}
