// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ConnectedGridAccelerator.ManagementApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ODataQueryContext
    {
        /// <summary>
        /// Initializes a new instance of the ODataQueryContext class.
        /// </summary>
        public ODataQueryContext()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ODataQueryContext class.
        /// </summary>
        public ODataQueryContext(IEdmModel model = default(IEdmModel), IEdmType elementType = default(IEdmType), string elementClrType = default(string))
        {
            Model = model;
            ElementType = elementType;
            ElementClrType = elementClrType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "model")]
        public IEdmModel Model { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "elementType")]
        public IEdmType ElementType { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "elementClrType")]
        public string ElementClrType { get; private set; }

    }
}
