// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ConnectedGridAccelerator.ManagementApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OntologyUpdate
    {
        /// <summary>
        /// Initializes a new instance of the OntologyUpdate class.
        /// </summary>
        public OntologyUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OntologyUpdate class.
        /// </summary>
        /// <param name="loaded">Switching an ontology from loaded false to
        /// true switches all its associated extended types to not Disabled
        /// unless they are also associated with another not loaded ontology.
        /// Switching an ontology from loaded true to false switches all its
        /// associated extended types to Disabled unless they are also
        /// associated with another loaded ontology.</param>
        public OntologyUpdate(bool? loaded = default(bool?))
        {
            Loaded = loaded;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets switching an ontology from loaded false to true
        /// switches all its associated extended types to not Disabled unless
        /// they are also associated with another not loaded ontology.
        /// Switching an ontology from loaded true to false switches all its
        /// associated extended types to Disabled unless they are also
        /// associated with another loaded ontology.
        /// </summary>
        [JsonProperty(PropertyName = "loaded")]
        public bool? Loaded { get; set; }

    }
}
