// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ConnectedGridAccelerator.ManagementApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SingleValueNode
    {
        /// <summary>
        /// Initializes a new instance of the SingleValueNode class.
        /// </summary>
        public SingleValueNode()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SingleValueNode class.
        /// </summary>
        public SingleValueNode(IEdmTypeReference typeReference = default(IEdmTypeReference), int? kind = default(int?))
        {
            TypeReference = typeReference;
            Kind = kind;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "typeReference")]
        public IEdmTypeReference TypeReference { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "kind")]
        public int? Kind { get; private set; }

    }
}
