// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ConnectedGridAccelerator.ManagementApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Space retrieve without child objects
    /// </summary>
    public partial class SpaceRetrieve
    {
        /// <summary>
        /// Initializes a new instance of the SpaceRetrieve class.
        /// </summary>
        public SpaceRetrieve()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SpaceRetrieve class.
        /// </summary>
        /// <param name="id">The identifier</param>
        /// <param name="typeId">Type identifier</param>
        /// <param name="subtypeId">Subtype identifier</param>
        /// <param name="statusId">Status identifier</param>
        /// <param name="friendlyName">Optional friendly name</param>
        /// <param name="type">Primary space type</param>
        /// <param name="parentSpaceId">The space's parent space</param>
        /// <param name="subtype">Space subtype</param>
        /// <param name="location">Optional physical location for the
        /// space</param>
        /// <param name="timeZoneId">Optional time zone identifier for the
        /// space</param>
        /// <param name="status">The status</param>
        /// <param name="effectiveTimeZoneId">Same as TimeZoneId, if defined.
        /// Otherwise same as EffectiveTimeZoneId of parent space</param>
        public SpaceRetrieve(System.Guid id, string name, int typeId, int subtypeId, int statusId, string description = default(string), string friendlyName = default(string), string type = default(string), System.Guid? parentSpaceId = default(System.Guid?), string subtype = default(string), Location location = default(Location), int? timeZoneId = default(int?), string status = default(string), string fullName = default(string), System.Collections.Generic.IList<string> spacePaths = default(System.Collections.Generic.IList<string>), Location effectiveLocation = default(Location), int? effectiveTimeZoneId = default(int?))
        {
            Id = id;
            Name = name;
            Description = description;
            FriendlyName = friendlyName;
            Type = type;
            TypeId = typeId;
            ParentSpaceId = parentSpaceId;
            Subtype = subtype;
            SubtypeId = subtypeId;
            Location = location;
            TimeZoneId = timeZoneId;
            Status = status;
            StatusId = statusId;
            FullName = fullName;
            SpacePaths = spacePaths;
            EffectiveLocation = effectiveLocation;
            EffectiveTimeZoneId = effectiveTimeZoneId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the identifier
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets optional friendly name
        /// </summary>
        [JsonProperty(PropertyName = "friendlyName")]
        public string FriendlyName { get; set; }

        /// <summary>
        /// Gets or sets primary space type
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets type identifier
        /// </summary>
        [JsonProperty(PropertyName = "typeId")]
        public int TypeId { get; set; }

        /// <summary>
        /// Gets or sets the space's parent space
        /// </summary>
        [JsonProperty(PropertyName = "parentSpaceId")]
        public System.Guid? ParentSpaceId { get; set; }

        /// <summary>
        /// Gets or sets space subtype
        /// </summary>
        [JsonProperty(PropertyName = "subtype")]
        public string Subtype { get; set; }

        /// <summary>
        /// Gets or sets subtype identifier
        /// </summary>
        [JsonProperty(PropertyName = "subtypeId")]
        public int SubtypeId { get; set; }

        /// <summary>
        /// Gets or sets optional physical location for the space
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public Location Location { get; set; }

        /// <summary>
        /// Gets or sets optional time zone identifier for the space
        /// </summary>
        [JsonProperty(PropertyName = "timeZoneId")]
        public int? TimeZoneId { get; set; }

        /// <summary>
        /// Gets or sets the status
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets status identifier
        /// </summary>
        [JsonProperty(PropertyName = "statusId")]
        public int StatusId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fullName")]
        public string FullName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "spacePaths")]
        public System.Collections.Generic.IList<string> SpacePaths { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "effectiveLocation")]
        public Location EffectiveLocation { get; set; }

        /// <summary>
        /// Gets or sets same as TimeZoneId, if defined. Otherwise same as
        /// EffectiveTimeZoneId of parent space
        /// </summary>
        [JsonProperty(PropertyName = "effectiveTimeZoneId")]
        public int? EffectiveTimeZoneId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Location != null)
            {
                Location.Validate();
            }
            if (EffectiveLocation != null)
            {
                EffectiveLocation.Validate();
            }
        }
    }
}
