// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ConnectedGridAccelerator.ManagementApi
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Matchers operations.
    /// </summary>
    public partial interface IMatchers
    {
        /// <summary>
        /// Retrieves matchers
        /// </summary>
        /// <param name='ids'>
        /// Optional ';' delimited list of ids
        /// </param>
        /// <param name='names'>
        /// Optional ';' delimited list of names
        /// </param>
        /// <param name='includes'>
        /// Comma separated list of what to include, for example
        /// "Space,Condition". Defaults to None. Possible values include:
        /// 'None', 'Description', 'FullPath', 'Space', 'Conditions',
        /// 'UserDefinedFunctions'
        /// </param>
        /// <param name='spaceId'>
        /// Optionally filter on objects based on their location in the
        /// topology relative to the specified spaceId
        /// </param>
        /// <param name='traverse'>
        /// None (the default) for the specified spaceId only, Down for space
        /// and descendants, Up for spaceId and ancestors, Any for both.
        /// Possible values include: 'None', 'Down', 'Up', 'Span'
        /// </param>
        /// <param name='minLevel'>
        /// Optional filter on minimum level, inclusive
        /// </param>
        /// <param name='maxLevel'>
        /// Optional filter on maximum level, inclusive
        /// </param>
        /// <param name='minRelative'>
        /// Specify if min level is absolute or relative
        /// </param>
        /// <param name='maxRelative'>
        /// Specify if max level is absolute or relative
        /// </param>
        /// <param name='filter'>
        /// Odata Filter parameter
        /// </param>
        /// <param name='orderby'>
        /// Odata OrderBy parameter
        /// </param>
        /// <param name='skip'>
        /// Odata Skip parameter
        /// </param>
        /// <param name='top'>
        /// Odata Top parameter
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorInformationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        System.Threading.Tasks.Task<HttpOperationResponse<System.Collections.Generic.IList<MatcherRetrieve>>> RetrieveWithHttpMessagesAsync(string ids = default(string), string names = default(string), string includes = default(string), System.Guid? spaceId = default(System.Guid?), string traverse = default(string), int? minLevel = default(int?), int? maxLevel = default(int?), bool? minRelative = default(bool?), bool? maxRelative = default(bool?), string filter = default(string), string orderby = default(string), int? skip = default(int?), int? top = default(int?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Creates a matcher
        /// </summary>
        /// <param name='data'>
        /// The matcher information
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorInformationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<HttpOperationResponse<System.Guid?>> CreateWithHttpMessagesAsync(MatcherCreate data, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Retrieves a matcher
        /// </summary>
        /// <param name='id'>
        /// Matcher identifier
        /// </param>
        /// <param name='includes'>
        /// Comma separated list of what to include. Possible values include:
        /// 'None', 'Description', 'FullPath', 'Space', 'Conditions',
        /// 'UserDefinedFunctions'
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorInformationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        System.Threading.Tasks.Task<HttpOperationResponse<MatcherRetrieve>> RetrieveByIdWithHttpMessagesAsync(System.Guid id, string includes = default(string), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Deletes the given matcher
        /// </summary>
        /// <param name='id'>
        /// Matcher identifier
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorInformationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        System.Threading.Tasks.Task<HttpOperationResponse> DeleteWithHttpMessagesAsync(System.Guid id, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update a matcher
        /// </summary>
        /// <param name='id'>
        /// Matcher identifier
        /// </param>
        /// <param name='data'>
        /// The matcher information
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorInformationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        System.Threading.Tasks.Task<HttpOperationResponse> UpdateWithHttpMessagesAsync(System.Guid id, MatcherUpdate data, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Evaluates the matcher for a sensor
        /// </summary>
        /// <param name='id'>
        /// Matcher identifier
        /// </param>
        /// <param name='sensorId'>
        /// Sensor identifier
        /// </param>
        /// <param name='enableLogging'>
        /// If true, return verbose logs for the evaluation
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ErrorInformationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        System.Threading.Tasks.Task<HttpOperationResponse<MatcherEvaluationResults>> EvaluateWithHttpMessagesAsync(System.Guid id, System.Guid sensorId, bool? enableLogging = default(bool?), System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
