// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace ConnectedGridAccelerator.ManagementApi
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Users.
    /// </summary>
    public static partial class UsersExtensions
    {
            /// <summary>
            /// Gets a list of users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='upn'>
            /// Optional filter on user UPN
            /// </param>
            /// <param name='firstName'>
            /// Optional filter on first name
            /// </param>
            /// <param name='lastName'>
            /// Optional filter on last name
            /// </param>
            /// <param name='includes'>
            /// Comma separated list of what to include, for example "Space". Defaults to
            /// None. A user can request their own RoleAssignments by passing in the
            /// "RoleAssigments" include parameter, but they cannot request the role
            /// assignments of others. Possible values include: 'None', 'FullPath',
            /// 'Location', 'Properties', 'RoleAssignments', 'Space'
            /// </param>
            /// <param name='propertyKey'>
            /// Optional filter on objects that have the given property key defined
            /// </param>
            /// <param name='propertyValue'>
            /// Optional filter on the value of the given property key
            /// </param>
            /// <param name='propertyValueSearchType'>
            /// Optional type of search on property value. Contains or Equals. Defaults to
            /// Equals. Possible values include: 'Equals', 'Contains'
            /// </param>
            /// <param name='spaceId'>
            /// Optionally filter on objects based on their location in the topology
            /// relative to the specified spaceId
            /// </param>
            /// <param name='traverse'>
            /// None (the default) for the specified spaceId only, Down for space and
            /// descendants, Up for spaceId and ancestors, Any for both. Possible values
            /// include: 'None', 'Down', 'Up', 'Span'
            /// </param>
            /// <param name='minLevel'>
            /// Optional filter on minimum level, inclusive
            /// </param>
            /// <param name='maxLevel'>
            /// Optional filter on maximum level, inclusive
            /// </param>
            /// <param name='minRelative'>
            /// Specify if min level is absolute or relative
            /// </param>
            /// <param name='maxRelative'>
            /// Specify if max level is absolute or relative
            /// </param>
            /// <param name='filter'>
            /// Odata Filter parameter
            /// </param>
            /// <param name='orderby'>
            /// Odata OrderBy parameter
            /// </param>
            /// <param name='skip'>
            /// Odata Skip parameter
            /// </param>
            /// <param name='top'>
            /// Odata Top parameter
            /// </param>
            public static System.Collections.Generic.IList<UserRetrieve> Retrieve(this IUsers operations, string upn = default(string), string firstName = default(string), string lastName = default(string), string includes = default(string), string propertyKey = default(string), string propertyValue = default(string), string propertyValueSearchType = default(string), System.Guid? spaceId = default(System.Guid?), string traverse = default(string), int? minLevel = default(int?), int? maxLevel = default(int?), bool? minRelative = default(bool?), bool? maxRelative = default(bool?), string filter = default(string), string orderby = default(string), int? skip = default(int?), int? top = default(int?))
            {
                return operations.RetrieveAsync(upn, firstName, lastName, includes, propertyKey, propertyValue, propertyValueSearchType, spaceId, traverse, minLevel, maxLevel, minRelative, maxRelative, filter, orderby, skip, top).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets a list of users
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='upn'>
            /// Optional filter on user UPN
            /// </param>
            /// <param name='firstName'>
            /// Optional filter on first name
            /// </param>
            /// <param name='lastName'>
            /// Optional filter on last name
            /// </param>
            /// <param name='includes'>
            /// Comma separated list of what to include, for example "Space". Defaults to
            /// None. A user can request their own RoleAssignments by passing in the
            /// "RoleAssigments" include parameter, but they cannot request the role
            /// assignments of others. Possible values include: 'None', 'FullPath',
            /// 'Location', 'Properties', 'RoleAssignments', 'Space'
            /// </param>
            /// <param name='propertyKey'>
            /// Optional filter on objects that have the given property key defined
            /// </param>
            /// <param name='propertyValue'>
            /// Optional filter on the value of the given property key
            /// </param>
            /// <param name='propertyValueSearchType'>
            /// Optional type of search on property value. Contains or Equals. Defaults to
            /// Equals. Possible values include: 'Equals', 'Contains'
            /// </param>
            /// <param name='spaceId'>
            /// Optionally filter on objects based on their location in the topology
            /// relative to the specified spaceId
            /// </param>
            /// <param name='traverse'>
            /// None (the default) for the specified spaceId only, Down for space and
            /// descendants, Up for spaceId and ancestors, Any for both. Possible values
            /// include: 'None', 'Down', 'Up', 'Span'
            /// </param>
            /// <param name='minLevel'>
            /// Optional filter on minimum level, inclusive
            /// </param>
            /// <param name='maxLevel'>
            /// Optional filter on maximum level, inclusive
            /// </param>
            /// <param name='minRelative'>
            /// Specify if min level is absolute or relative
            /// </param>
            /// <param name='maxRelative'>
            /// Specify if max level is absolute or relative
            /// </param>
            /// <param name='filter'>
            /// Odata Filter parameter
            /// </param>
            /// <param name='orderby'>
            /// Odata OrderBy parameter
            /// </param>
            /// <param name='skip'>
            /// Odata Skip parameter
            /// </param>
            /// <param name='top'>
            /// Odata Top parameter
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<System.Collections.Generic.IList<UserRetrieve>> RetrieveAsync(this IUsers operations, string upn = default(string), string firstName = default(string), string lastName = default(string), string includes = default(string), string propertyKey = default(string), string propertyValue = default(string), string propertyValueSearchType = default(string), System.Guid? spaceId = default(System.Guid?), string traverse = default(string), int? minLevel = default(int?), int? maxLevel = default(int?), bool? minRelative = default(bool?), bool? maxRelative = default(bool?), string filter = default(string), string orderby = default(string), int? skip = default(int?), int? top = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.RetrieveWithHttpMessagesAsync(upn, firstName, lastName, includes, propertyKey, propertyValue, propertyValueSearchType, spaceId, traverse, minLevel, maxLevel, minRelative, maxRelative, filter, orderby, skip, top, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Creates or updates a user, using SpaceId and upn as lookup keys
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='data'>
            /// User settings
            /// </param>
            public static System.Guid? CreateOrUpdate(this IUsers operations, UserCreateWithSpace data)
            {
                return operations.CreateOrUpdateAsync(data).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates or updates a user, using SpaceId and upn as lookup keys
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='data'>
            /// User settings
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<System.Guid?> CreateOrUpdateAsync(this IUsers operations, UserCreateWithSpace data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.CreateOrUpdateWithHttpMessagesAsync(data, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets a specific user
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// User identifier
            /// </param>
            /// <param name='includes'>
            /// Comma separated list of what to include, for example "Space". Defaults to
            /// None. A user can request their own RoleAssignments by passing in the
            /// "RoleAssigments" include parameter, but they cannot request the role
            /// assignments of others. Possible values include: 'None', 'FullPath',
            /// 'Location', 'Properties', 'RoleAssignments', 'Space'
            /// </param>
            public static UserRetrieve RetrieveById(this IUsers operations, System.Guid id, string includes = default(string))
            {
                return operations.RetrieveByIdAsync(id, includes).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets a specific user
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// User identifier
            /// </param>
            /// <param name='includes'>
            /// Comma separated list of what to include, for example "Space". Defaults to
            /// None. A user can request their own RoleAssignments by passing in the
            /// "RoleAssigments" include parameter, but they cannot request the role
            /// assignments of others. Possible values include: 'None', 'FullPath',
            /// 'Location', 'Properties', 'RoleAssignments', 'Space'
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<UserRetrieve> RetrieveByIdAsync(this IUsers operations, System.Guid id, string includes = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.RetrieveByIdWithHttpMessagesAsync(id, includes, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Deletes a user
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// User Id
            /// </param>
            public static void Delete(this IUsers operations, System.Guid id)
            {
                operations.DeleteAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes a user
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// User Id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task DeleteAsync(this IUsers operations, System.Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.DeleteWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Updates a user
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// User identifier
            /// </param>
            /// <param name='data'>
            /// User settings
            /// </param>
            public static void Update(this IUsers operations, System.Guid id, UserUpdate data)
            {
                operations.UpdateAsync(id, data).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Updates a user
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// User identifier
            /// </param>
            /// <param name='data'>
            /// User settings
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task UpdateAsync(this IUsers operations, System.Guid id, UserUpdate data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.UpdateWithHttpMessagesAsync(id, data, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Gets a list of blobs
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='names'>
            /// Optional ';' or ',' delimited list of blob names to filter by
            /// </param>
            /// <param name='ids'>
            /// Optional ';' or ',' delimited list of ids to filter by
            /// </param>
            /// <param name='sharings'>
            /// Optional ';' or ',' delimited list of Sharing modes to filter by
            /// </param>
            /// <param name='types'>
            /// Optional ';' or ',' delimited list of types to filter by
            /// </param>
            /// <param name='subtypes'>
            /// Optional ';' or ',' delimited list of subtypes to filter by
            /// </param>
            /// <param name='includes'>
            /// Comma separated list of what to include, for example
            /// "ContentInfo,Description". Defaults to None. Possible values include:
            /// 'None', 'ContentInfo', 'Description', 'FullPath', 'Types'
            /// </param>
            /// <param name='spaceId'>
            /// Optionally filter on objects based on their location in the topology
            /// relative to the specified spaceId
            /// </param>
            /// <param name='traverse'>
            /// None (the default) for the specified spaceId only, Down for space and
            /// descendants, Up for spaceId and ancestors, Any for both. Possible values
            /// include: 'None', 'Down', 'Up', 'Span'
            /// </param>
            /// <param name='minLevel'>
            /// Optional filter on minimum level, inclusive
            /// </param>
            /// <param name='maxLevel'>
            /// Optional filter on maximum level, inclusive
            /// </param>
            /// <param name='minRelative'>
            /// Specify if min level is absolute or relative
            /// </param>
            /// <param name='maxRelative'>
            /// Specify if max level is absolute or relative
            /// </param>
            /// <param name='filter'>
            /// Odata Filter parameter
            /// </param>
            /// <param name='orderby'>
            /// Odata OrderBy parameter
            /// </param>
            /// <param name='skip'>
            /// Odata Skip parameter
            /// </param>
            /// <param name='top'>
            /// Odata Top parameter
            /// </param>
            public static System.Collections.Generic.IList<BlobMetadataRetrieve> RetrieveBlobMetadata(this IUsers operations, string names = default(string), string ids = default(string), string sharings = default(string), string types = default(string), string subtypes = default(string), string includes = default(string), System.Guid? spaceId = default(System.Guid?), string traverse = default(string), int? minLevel = default(int?), int? maxLevel = default(int?), bool? minRelative = default(bool?), bool? maxRelative = default(bool?), string filter = default(string), string orderby = default(string), int? skip = default(int?), int? top = default(int?))
            {
                return operations.RetrieveBlobMetadataAsync(names, ids, sharings, types, subtypes, includes, spaceId, traverse, minLevel, maxLevel, minRelative, maxRelative, filter, orderby, skip, top).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets a list of blobs
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='names'>
            /// Optional ';' or ',' delimited list of blob names to filter by
            /// </param>
            /// <param name='ids'>
            /// Optional ';' or ',' delimited list of ids to filter by
            /// </param>
            /// <param name='sharings'>
            /// Optional ';' or ',' delimited list of Sharing modes to filter by
            /// </param>
            /// <param name='types'>
            /// Optional ';' or ',' delimited list of types to filter by
            /// </param>
            /// <param name='subtypes'>
            /// Optional ';' or ',' delimited list of subtypes to filter by
            /// </param>
            /// <param name='includes'>
            /// Comma separated list of what to include, for example
            /// "ContentInfo,Description". Defaults to None. Possible values include:
            /// 'None', 'ContentInfo', 'Description', 'FullPath', 'Types'
            /// </param>
            /// <param name='spaceId'>
            /// Optionally filter on objects based on their location in the topology
            /// relative to the specified spaceId
            /// </param>
            /// <param name='traverse'>
            /// None (the default) for the specified spaceId only, Down for space and
            /// descendants, Up for spaceId and ancestors, Any for both. Possible values
            /// include: 'None', 'Down', 'Up', 'Span'
            /// </param>
            /// <param name='minLevel'>
            /// Optional filter on minimum level, inclusive
            /// </param>
            /// <param name='maxLevel'>
            /// Optional filter on maximum level, inclusive
            /// </param>
            /// <param name='minRelative'>
            /// Specify if min level is absolute or relative
            /// </param>
            /// <param name='maxRelative'>
            /// Specify if max level is absolute or relative
            /// </param>
            /// <param name='filter'>
            /// Odata Filter parameter
            /// </param>
            /// <param name='orderby'>
            /// Odata OrderBy parameter
            /// </param>
            /// <param name='skip'>
            /// Odata Skip parameter
            /// </param>
            /// <param name='top'>
            /// Odata Top parameter
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<System.Collections.Generic.IList<BlobMetadataRetrieve>> RetrieveBlobMetadataAsync(this IUsers operations, string names = default(string), string ids = default(string), string sharings = default(string), string types = default(string), string subtypes = default(string), string includes = default(string), System.Guid? spaceId = default(System.Guid?), string traverse = default(string), int? minLevel = default(int?), int? maxLevel = default(int?), bool? minRelative = default(bool?), bool? maxRelative = default(bool?), string filter = default(string), string orderby = default(string), int? skip = default(int?), int? top = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.RetrieveBlobMetadataWithHttpMessagesAsync(names, ids, sharings, types, subtypes, includes, spaceId, traverse, minLevel, maxLevel, minRelative, maxRelative, filter, orderby, skip, top, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Creates a blob
            /// </summary>
            /// <remarks>
            /// This is a multi-part request. For more information, see sample app or doc
            /// examples.
            /// Key value pairs specified in the Content-Disposition header in the
            /// blob-chunk of the multipart request will be preserved as meta-data on the
            /// stored blob.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='metadata'>
            /// The mime type of this parameter is "application/json" and its schema is
            /// #/definitions/BlobMetadataCreate
            /// </param>
            public static System.Guid? CreateBlob(this IUsers operations, string metadata)
            {
                return operations.CreateBlobAsync(metadata).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates a blob
            /// </summary>
            /// <remarks>
            /// This is a multi-part request. For more information, see sample app or doc
            /// examples.
            /// Key value pairs specified in the Content-Disposition header in the
            /// blob-chunk of the multipart request will be preserved as meta-data on the
            /// stored blob.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='metadata'>
            /// The mime type of this parameter is "application/json" and its schema is
            /// #/definitions/BlobMetadataCreate
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<System.Guid?> CreateBlobAsync(this IUsers operations, string metadata, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.CreateBlobWithHttpMessagesAsync(metadata, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Gets a blob
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Blob Id
            /// </param>
            /// <param name='includes'>
            /// Comma separated list of what to include, for example
            /// "ContentInfo,Description". Defaults to None. Possible values include:
            /// 'None', 'ContentInfo', 'Description', 'FullPath', 'Types'
            /// </param>
            public static BlobMetadataRetrieve RetrieveBlobMetadataById(this IUsers operations, System.Guid id, string includes = default(string))
            {
                return operations.RetrieveBlobMetadataByIdAsync(id, includes).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets a blob
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Blob Id
            /// </param>
            /// <param name='includes'>
            /// Comma separated list of what to include, for example
            /// "ContentInfo,Description". Defaults to None. Possible values include:
            /// 'None', 'ContentInfo', 'Description', 'FullPath', 'Types'
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<BlobMetadataRetrieve> RetrieveBlobMetadataByIdAsync(this IUsers operations, System.Guid id, string includes = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.RetrieveBlobMetadataByIdWithHttpMessagesAsync(id, includes, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Deletes a blob
            /// </summary>
            /// <remarks>
            /// Deleting a blob will delete its metadata, its content (all versions) and
            /// its associations
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Blob Id
            /// </param>
            public static void DeleteBlob(this IUsers operations, System.Guid id)
            {
                operations.DeleteBlobAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes a blob
            /// </summary>
            /// <remarks>
            /// Deleting a blob will delete its metadata, its content (all versions) and
            /// its associations
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Blob Id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task DeleteBlobAsync(this IUsers operations, System.Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.DeleteBlobWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Updates a blob
            /// </summary>
            /// <remarks>
            /// This is a multi-part request. For more information, see sample app or doc
            /// examples.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// blob Id
            /// </param>
            /// <param name='metadata'>
            /// The mime type of this parameter is "application/json" and its schema is
            /// #/definitions/BlobMetadataUpdate
            /// </param>
            public static void UpdateBlob(this IUsers operations, System.Guid id, string metadata)
            {
                operations.UpdateBlobAsync(id, metadata).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Updates a blob
            /// </summary>
            /// <remarks>
            /// This is a multi-part request. For more information, see sample app or doc
            /// examples.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// blob Id
            /// </param>
            /// <param name='metadata'>
            /// The mime type of this parameter is "application/json" and its schema is
            /// #/definitions/BlobMetadataUpdate
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task UpdateBlobAsync(this IUsers operations, System.Guid id, string metadata, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.UpdateBlobWithHttpMessagesAsync(id, metadata, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Gets the contents of the given version of the given blob
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// blob id
            /// </param>
            /// <param name='version'>
            /// blob content version
            /// </param>
            public static System.IO.Stream GetBlobContents(this IUsers operations, System.Guid id, long version)
            {
                return operations.GetBlobContentsAsync(id, version).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the contents of the given version of the given blob
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// blob id
            /// </param>
            /// <param name='version'>
            /// blob content version
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<System.IO.Stream> GetBlobContentsAsync(this IUsers operations, System.Guid id, long version, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                var _result = await operations.GetBlobContentsWithHttpMessagesAsync(id, version, null, cancellationToken).ConfigureAwait(false);
                _result.Request.Dispose();
                return _result.Body;
            }

            /// <summary>
            /// Delete the contents of the given version of the given blob
            /// </summary>
            /// <remarks>
            /// Delete will fail if this version has any associations
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// blob id
            /// </param>
            /// <param name='version'>
            /// blob version
            /// </param>
            public static void DeleteBlobContents(this IUsers operations, System.Guid id, long version)
            {
                operations.DeleteBlobContentsAsync(id, version).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete the contents of the given version of the given blob
            /// </summary>
            /// <remarks>
            /// Delete will fail if this version has any associations
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// blob id
            /// </param>
            /// <param name='version'>
            /// blob version
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task DeleteBlobContentsAsync(this IUsers operations, System.Guid id, long version, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.DeleteBlobContentsWithHttpMessagesAsync(id, version, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Gets the contents of the latest version of the given blob
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// blob id
            /// </param>
            public static System.IO.Stream GetLatestBlobContents(this IUsers operations, System.Guid id)
            {
                return operations.GetLatestBlobContentsAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the contents of the latest version of the given blob
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// blob id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<System.IO.Stream> GetLatestBlobContentsAsync(this IUsers operations, System.Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                var _result = await operations.GetLatestBlobContentsWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false);
                _result.Request.Dispose();
                return _result.Body;
            }

            /// <summary>
            /// Gets the value of a property
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Parent Id
            /// </param>
            /// <param name='name'>
            /// Property name
            /// </param>
            public static string RetrieveProperty(this IUsers operations, System.Guid id, string name)
            {
                return operations.RetrievePropertyAsync(id, name).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets the value of a property
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Parent Id
            /// </param>
            /// <param name='name'>
            /// Property name
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<string> RetrievePropertyAsync(this IUsers operations, System.Guid id, string name, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.RetrievePropertyWithHttpMessagesAsync(id, name, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Deletes the given property value
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Parent Id
            /// </param>
            /// <param name='name'>
            /// Property name
            /// </param>
            public static void DeleteProperty(this IUsers operations, System.Guid id, string name)
            {
                operations.DeletePropertyAsync(id, name).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes the given property value
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Parent Id
            /// </param>
            /// <param name='name'>
            /// Property name
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task DeletePropertyAsync(this IUsers operations, System.Guid id, string name, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.DeletePropertyWithHttpMessagesAsync(id, name, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Creates or updates property values
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Parent Id
            /// </param>
            /// <param name='data'>
            /// The properties
            /// </param>
            public static object UpdateProperties(this IUsers operations, System.Guid id, System.Collections.Generic.IList<ExtendedPropertyCreate> data)
            {
                return operations.UpdatePropertiesAsync(id, data).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates or updates property values
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Parent Id
            /// </param>
            /// <param name='data'>
            /// The properties
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<object> UpdatePropertiesAsync(this IUsers operations, System.Guid id, System.Collections.Generic.IList<ExtendedPropertyCreate> data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.UpdatePropertiesWithHttpMessagesAsync(id, data, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Creates a property value
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Parent Id
            /// </param>
            /// <param name='data'>
            /// Extended property data
            /// </param>
            public static string CreateProperty(this IUsers operations, System.Guid id, ExtendedPropertyCreate data)
            {
                return operations.CreatePropertyAsync(id, data).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates a property value
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Parent Id
            /// </param>
            /// <param name='data'>
            /// Extended property data
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task<string> CreatePropertyAsync(this IUsers operations, System.Guid id, ExtendedPropertyCreate data, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                using (var _result = await operations.CreatePropertyWithHttpMessagesAsync(id, data, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Deletes all property values
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Parent Id
            /// </param>
            public static void DeleteProperties(this IUsers operations, System.Guid id)
            {
                operations.DeletePropertiesAsync(id).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes all property values
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Parent Id
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async System.Threading.Tasks.Task DeletePropertiesAsync(this IUsers operations, System.Guid id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
            {
                (await operations.DeletePropertiesWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
